### ISSUE TITLE
OSX: IOError on writing to sys.stdout if lots of data.

### ISSUE THREAD

**Issue by StefanNyman** [jumpstarter-io/jsc#46]
```
running command: unzip -d /app/code/src/wp-content/themes/ tint-themeskingdom.zip
Archive:  tint-themeskingdom.zip
   creating: /app/code/src/wp-content/themes/tint-themeskingdom/
  inflating: /app/code/src/wp-content/themes/tint-themeskingdom/404.php
  inflating: /app/code/src/wp-content/themes/tint-themeskingdom/admin-settings.php
 extracting: /app/code/src/wp-content/themes/tint-themeskingdom/archive-portfolio.php
  inflating: /app/code/src/wp-content/themes/tint-themeskingdom/archive.php
  inflating: /app/code/src/wp-content/themes/tint-themeskingdom/comments.php
  inflating: /app/code/src/wp-content/themes/tint-themeskingdom/footer.php
  inflating: /app/code/src/wp-content/themes/tint-themeskingdom/functions.php
  inflating: /app/code/src/wp-content/themes/tint-themeskingdom/header.php
   creating: /app/code/src/wp-content/themes/tint-themeskingdom/inc/
  inflating: /app/code/src/wp-content/themes/tint-themeskingdom/inc/admin-settings.php
  inflating: /app/code/src/wp-content/themes/tint-themeskingdom/inc/class-tgm-plugin-activation.php
 extracting: /app/code/src/wp-content/themes/tint-themeskingdom/inc/custom-taxonomies.php  Traceback (most recent call last):
  File "/Users/z/jsc/jsc/client.py", line 579, in <module>
    main()
  File "/Users/z/jsc/jsc/client.py", line 549, in main
    console.cmdloop_with_keyboard_interrupt("Welcome to jsc!")
  File "/Users/z/jsc/jsc/client.py", line 163, in cmdloop_with_keyboard_interrupt
    self.cmdloop(intro="")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/Users/z/jsc/jsc/client.py", line 131, in fn
    return func(self, {k.lstrip("<").rstrip(">"): opt[k] for k in opt})
  File "/Users/z/jsc/jsc/client.py", line 239, in do_deploy
    state = recipe.run(self._rpc, rec, args['--dev'])
  File "/Users/z/jsc/jsc/recipe.py", line 22, in run
    state = rpc.call("rc_" + command, {"args": args, "state": state})
  File "/Users/z/jsc/jsc/sshjsonrpcposix.py", line 55, in call
    sys.stdout.flush()
IOError: [Errno 35] Resource temporarily unavailable
```

Adding the following to sshjsonrpc seems to solve the issue on OSX, but it might not be a good solution:

``` python
stdout_fd = sys.stdout.fileno()
flags = fcntl.fcntl(stdout_fd, fcntl.F_GETFL)
fcntl.fcntl(stdout_fd, fcntl.F_SETFL, flags & ~os.O_NONBLOCK)
```

**Comment by thorwald** [comment]
fixed in 5.3
